version: "3.8"
services:
    web:
        # Build image from source in localhost only
        # Use remote image instead in other cases
        build: .
        environment:
            JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}
            ACTIVE_PROFILE: ${ACTIVE_PROFILE:?string}
        expose:
            - 8082
        ports:
            - "${LAUNCH_PORT:?number}:8082"
        volumes:
            - logs:/app/logs
        restart: on-failure
volumes:
    logs:
