version: '3.8' # Must be quoted
services:
    web:
        # Build image from source in localhost only
        # Use remote image instead in other cases
        build: .
        # Pass environment variables to container
        environment:
            - server.port=${PORT?}
            - spring.profiles.active=${ACTIVE_PROFILE?}
            - JAVA_TOOL_OPTIONS=${JAVA_TOOL_OPTIONS}
        expose:
            - ${PORT?}
        ports:
            - 8082:${PORT?}
        restart: on-failure
        volumes:
            - logs:/app/logs
volumes:
    logs:
